"""add_content_text_to_proposal_sections

Revision ID: 665cd05ee540
Revises: 602668b891d0
Create Date: 2026-06-19 18:53:21.450588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '665cd05ee540'
down_revision: Union[str, Sequence[str], None] = '602668b891d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company_documents', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('company_documents', 'file_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('company_documents', 's3_key',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('company_documents', 'content_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('company_documents', 'status',
               existing_type=sa.VARCHAR(length=9),
               nullable=False)
    op.alter_column('company_documents', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('grants', 'external_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('grants', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('grants', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('grants', 'deadline',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('grants', 'sector_tags',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('grants', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.add_column('organizations', sa.Column('match_threshold', sa.Float(), nullable=False))
    op.add_column('organizations', sa.Column('alert_email_enabled', sa.Boolean(), nullable=False))
    op.alter_column('organizations', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('organizations', 'subscription_tier',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('organizations', 'countries_of_operation',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('organizations', 'core_technologies',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('organizations', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.add_column('proposal_sections', sa.Column('content_text', sa.Text(), nullable=True))
    op.alter_column('proposals', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('proposals', 'grant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('proposals', 'status',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'COMPLETED_WITH_ERRORS', 'FAILED', name='proposalstatus'),
               nullable=False)
    op.alter_column('proposals', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=6),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=6),
               nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('proposals', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('proposals', 'status',
               existing_type=sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'COMPLETED_WITH_ERRORS', 'FAILED', name='proposalstatus'),
               type_=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('proposals', 'grant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('proposals', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('proposal_sections', 'content_text')
    op.alter_column('organizations', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('organizations', 'core_technologies',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('organizations', 'countries_of_operation',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('organizations', 'subscription_tier',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('organizations', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('organizations', 'alert_email_enabled')
    op.drop_column('organizations', 'match_threshold')
    op.alter_column('grants', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('grants', 'sector_tags',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('grants', 'deadline',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('grants', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('grants', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('grants', 'external_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('company_documents', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('company_documents', 'status',
               existing_type=sa.VARCHAR(length=9),
               nullable=True)
    op.alter_column('company_documents', 'content_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('company_documents', 's3_key',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('company_documents', 'file_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('company_documents', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
